Import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

Read the excel file and drop all the rows with atleast one null value

In [2]:
dataset = pd.read_excel('file.xlsx')
dataset = dataset.dropna()
dataset

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365.0,71053.0,WHITE METAL LANTERN,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365.0,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365.0,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365.0,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587.0,22613.0,PACK OF 20 SPACEBOY NAPKINS,12.0,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587.0,22899.0,CHILDREN'S APRON DOLLY GIRL,6.0,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587.0,23254.0,CHILDRENS CUTLERY DOLLY GIRL,4.0,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587.0,23255.0,CHILDRENS CUTLERY CIRCUS PARADE,4.0,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587.0,22138.0,BAKING SET 9 PIECE RETROSPOT,3.0,2011-12-09 12:50:00,4.95,12680.0,France

Customers who have made a transaction between 1st Dec 2010 to 31st Aug 2011

In [3]:
training_data = dataset[(dataset['InvoiceDate'] >= '2010-12-01') & (dataset['InvoiceDate'] <= '2011-08-31')]
training_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365.0,71053.0,WHITE METAL LANTERN,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365.0,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365.0,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365.0,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
319395,564852.0,82552.0,WASHROOM METAL SIGN,10.0,2011-08-30 17:23:00,1.45,14976.0,United Kingdom
319396,564852.0,21756.0,BATH BUILDING BLOCK WORD,3.0,2011-08-30 17:23:00,5.95,14976.0,United Kingdom
319397,564852.0,21908.0,CHOCOLATE THIS WAY METAL SIGN,7.0,2011-08-30 17:23:00,2.10,14976.0,United Kingdom
319398,564852.0,22116.0,METAL SIGN HIS DINNER IS SERVED,10.0,2011-08-30 17:23:00,0.79,14976.0,United Kingdom
319399,564852.0,23091.0,ZINC HERB GARDEN CONTAINER,2.0,2011-08-30 17:23:00,6.25,14976.0,United Kingdom

Customers who have not made any subsequent purchase between Sep 2011 and Dec 2011

In [4]:
temp0_data = dataset[(dataset['InvoiceDate'] >= '2011-09-01') & (dataset['InvoiceDate'] <= '2011-12-31')]
temp0_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
320705,565080.0,20677.0,PINK POLKADOT BOWL,8.0,2011-09-01 08:25:00,1.25,13509.0,United Kingdom
320706,565080.0,22128.0,PARTY CONES CANDY ASSORTED,24.0,2011-09-01 08:25:00,1.25,13509.0,United Kingdom
320708,565082.0,22423.0,REGENCY CAKESTAND 3 TIER,2.0,2011-09-01 09:15:00,12.75,13305.0,United Kingdom
320709,565082.0,15060B,FAIRY CAKE DESIGN UMBRELLA,8.0,2011-09-01 09:15:00,3.75,13305.0,United Kingdom
320710,565082.0,23245.0,SET OF 3 REGENCY CAKE TINS,4.0,2011-09-01 09:15:00,4.95,13305.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587.0,22613.0,PACK OF 20 SPACEBOY NAPKINS,12.0,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587.0,22899.0,CHILDREN'S APRON DOLLY GIRL,6.0,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587.0,23254.0,CHILDRENS CUTLERY DOLLY GIRL,4.0,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587.0,23255.0,CHILDRENS CUTLERY CIRCUS PARADE,4.0,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587.0,22138.0,BAKING SET 9 PIECE RETROSPOT,3.0,2011-12-09 12:50:00,4.95,12680.0,France

In [5]:
temp0_customer_ids = list(set(list(temp0_data['CustomerID'])))
temp0_customer_ids

[16384.0,
 16385.0,
 16386.0,
 16389.0,
 16393.0,
 16394.0,
 16395.0,
 16399.0,
 16400.0,
 16401.0,
 16404.0,
 16406.0,
 16407.0,
 16409.0,
 16411.0,
 16412.0,
 16413.0,
 16414.0,
 16415.0,
 16416.0,
 16418.0,
 16422.0,
 16423.0,
 16426.0,
 16428.0,
 16430.0,
 16432.0,
 16433.0,
 16434.0,
 16438.0,
 16440.0,
 16441.0,
 16442.0,
 16444.0,
 16445.0,
 16446.0,
 16451.0,
 16454.0,
 16455.0,
 16456.0,
 16458.0,
 16460.0,
 16462.0,
 16463.0,
 16464.0,
 16466.0,
 16468.0,
 16469.0,
 16470.0,
 16474.0,
 16475.0,
 16477.0,
 16478.0,
 16479.0,
 16480.0,
 16482.0,
 16485.0,
 16488.0,
 16491.0,
 16493.0,
 16495.0,
 16496.0,
 16497.0,
 16500.0,
 16504.0,
 16505.0,
 16506.0,
 16511.0,
 16513.0,
 16515.0,
 16516.0,
 16518.0,
 16519.0,
 16523.0,
 16525.0,
 16527.0,
 16528.0,
 16531.0,
 16532.0,
 16533.0,
 16535.0,
 16539.0,
 16542.0,
 16549.0,
 16551.0,
 16554.0,
 16555.0,
 16556.0,
 16557.0,
 16558.0,
 16560.0,
 16561.0,
 16563.0,
 16566.0,
 16569.0,
 16570.0,
 16571.0,
 16573.0,
 16574.0,
 16584.0,
 16589.0,
 16591.0,
 16592.0,
 16593.0,
 16594.0,
 16595.0,
 16596.0,
 16597.0,
 16600.0,
 16601.0,
 16602.0,
 16603.0,
 16607.0,
 16609.0,
 16612.0,
 16613.0,
 16616.0,
 16618.0,
 16620.0,
 16621.0,
 16624.0,
 16626.0,
 16627.0,
 16628.0,
 16629.0,
 16633.0,
 16637.0,
 16638.0,
 16639.0,
 16642.0,
 16648.0,
 16650.0,
 16652.0,
 16653.0,
 16655.0,
 16656.0,
 16657.0,
 16660.0,
 16666.0,
 16667.0,
 16668.0,
 16669.0,
 16670.0,
 16671.0,
 16672.0,
 16674.0,
 16676.0,
 16678.0,
 16680.0,
 16681.0,
 16682.0,
 16684.0,
 16685.0,
 16686.0,
 16688.0,
 16689.0,
 16690.0,
 16693.0,
 16700.0,
 16701.0,
 16705.0,
 16706.0,
 16708.0,
 16709.0,
 16710.0,
 16711.0,
 16712.0,
 16713.0,
 16715.0,
 16717.0,
 16719.0,
 16720.0,
 16722.0,
 16723.0,
 16726.0,
 16728.0,
 16729.0,
 16730.0,
 16732.0,
 16734.0,
 16735.0,
 16737.0,
 16742.0,
 16743.0,
 16744.0,
 16745.0,
 16746.0,
 16747.0,
 16748.0,
 16750.0,
 16751.0,
 16753.0,
 16758.0,
 16759.0,
 16761.0,
 16762.0,
 16764.0,
 16767.0,
 16768.0,
 16770.0,
 16771.0,
 16773.0,
 16774.0,
 16775.0,
 16776.0,
 16777.0,
 16778.0,
 16779.0,
 16782.0,
 16784.0,
 16789.0,
 16790.0,
 16791.0,
 16793.0,
 16794.0,
 16796.0,
 16800.0,
 16803.0,
 16804.0,
 16808.0,
 16809.0,
 16811.0,
 16813.0,
 16814.0,
 16817.0,
 16818.0,
 16820.0,
 16824.0,
 16825.0,
 16826.0,
 16828.0,
 16830.0,
 16833.0,
 16836.0,
 16837.0,
 16839.0,
 16841.0,
 16842.0,
 16843.0,
 16846.0,
 16847.0,
 16848.0,
 16851.0,
 16852.0,
 16855.0,
 16856.0,
 16861.0,
 16863.0,
 16869.0,
 16871.0,
 16872.0,
 16873.0,
 16875.0,
 16877.0,
 16878.0,
 16880.0,
 16881.0,
 16882.0,
 16884.0,
 16885.0,
 16887.0,
 16891.0,
 16892.0,
 16895.0,
 16898.0,
 16899.0,
 16900.0,
 16903.0,
 16904.0,
 16905.0,
 16906.0,
 16907.0,
 16909.0,
 16910.0,
 16912.0,
 16914.0,
 16915.0,
 16916.0,
 16918.0,
 16921.0,
 16923.0,
 16924.0,
 16928.0,
 16929.0,
 16930.0,
 16931.0,
 16932.0,
 16933.0,
 16934.0,
 16936.0,
 16938.0,
 16940.0,
 16942.0,
 16945.0,
 16949.0,
 16950.0,
 16953.0,
 16954.0,
 16956.0,
 16959.0,
 16960.0,
 16966.0,
 16968.0,
 16969.0,
 16971.0,
 16978.0,
 16979.0,
 16982.0,
 16983.0,
 16984.0,
 16985.0,
 16986.0,
 16987.0,
 16988.0,
 16989.0,
 16992.0,
 16996.0,
 16999.0,
 17001.0,
 17002.0,
 17004.0,
 17006.0,
 17007.0,
 17010.0,
 17011.0,
 17014.0,
 17015.0,
 17017.0,
 17018.0,
 17019.0,
 17022.0,
 17024.0,
 17025.0,
 17027.0,
 17030.0,
 17031.0,
 17033.0,
 17034.0,
 17037.0,
 17038.0,
 17041.0,
 17042.0,
 17043.0,
 17044.0,
 17047.0,
 17049.0,
 17050.0,
 17052.0,
 17054.0,
 17058.0,
 17059.0,
 17061.0,
 17063.0,
 17064.0,
 17068.0,
 17069.0,
 17071.0,
 17073.0,
 17075.0,
 17076.0,
 17078.0,
 17079.0,
 17080.0,
 17081.0,
 17082.0,
 17084.0,
 17086.0,
 17088.0,
 17090.0,
 17091.0,
 17092.0,
 17095.0,
 17096.0,
 17097.0,
 17100.0,
 17101.0,
 17107.0,
 17109.0,
 17111.0,
 17114.0,
 17115.0,
 17119.0,
 17125.0,
 17131.0,
 17133.0,
 17135.0,
 17139.0,
 17144.0,
 17147.0,
 17148.0,
 17153.0,
 17154.0,
 17155.0,
 17157.0,
 17158.0,
 17159.0,
 17160.0,
 17162.0,
 17163.0,
 17164.0,
 17166.0,
 17169.0,
 17172.0,
 17173.0,
 17175.0,
 17180.0,
 17181.0,
 17183.0,
 17186.0,
 17188.0,
 17190.0,
 17191.0,
 17193.0,
 17197.0,
 17198.0,
 17201.0,
 17203.0,
 17205.0,
 17206.0,
 17211.0,
 17213.0,
 17214.0,
 17218.0,
 17219.0,
 17220.0,
 17221.0,
 17222.0,
 17227.0,
 17228.0,
 17229.0,
 17231.0,
 17232.0,
 17233.0,
 17235.0,
 17236.0,
 17237.0,
 17238.0,
 17243.0,
 17244.0,
 17247.0,
 17250.0,
 17253.0,
 17254.0,
 17255.0,
 17262.0,
 17266.0,
 17272.0,
 17274.0,
 17279.0,
 17284.0,
 17286.0,
 17287.0,
 17288.0,
 17289.0,
 17290.0,
 17293.0,
 17295.0,
 17297.0,
 17299.0,
 17301.0,
 17302.0,
 17306.0,
 17309.0,
 17311.0,
 17313.0,
 17314.0,
 17315.0,
 17317.0,
 17321.0,
 17323.0,
 17324.0,
 17329.0,
 17330.0,
 17333.0,
 17338.0,
 17339.0,
 17340.0,
 17344.0,
 17345.0,
 17346.0,
 17347.0,
 17348.0,
 17350.0,
 17351.0,
 17354.0,
 17357.0,
 17359.0,
 17360.0,
 17361.0,
 17364.0,
 17365.0,
 17368.0,
 17370.0,
 17371.0,
 17372.0,
 17373.0,
 17376.0,
 17377.0,
 17379.0,
 17381.0,
 17382.0,
 17383.0,
 17384.0,
 17385.0,
 17386.0,
 17387.0,
 17388.0,
 17389.0,
 17396.0,
 17397.0,
 17402.0,
 17403.0,
 17404.0,
 17405.0,
 17410.0,
 17411.0,
 17412.0,
 17414.0,
 17415.0,
 17416.0,
 17418.0,
 17419.0,
 17420.0,
 17422.0,
 17423.0,
 17425.0,
 17426.0,
 17427.0,
 17428.0,
 17430.0,
 17432.0,
 17433.0,
 17434.0,
 17436.0,
 17442.0,
 17447.0,
 17449.0,
 17450.0,
 17451.0,
 17453.0,
 17458.0,
 17459.0,
 17460.0,
 17461.0,
 17462.0,
 17463.0,
 17466.0,
 17468.0,
 17469.0,
 17470.0,
 17475.0,
 17480.0,
 17481.0,
 17483.0,
 17489.0,
 17490.0,
 17491.0,
 17495.0,
 17498.0,
 17500.0,
 17502.0,
 17503.0,
 17506.0,
 17509.0,
 17510.0,
 17511.0,
 17512.0,
 17513.0,
 17515.0,
 17516.0,
 17519.0,
 17520.0,
 17521.0,
 17522.0,
 17523.0,
 17526.0,
 17527.0,
 17528.0,
 17530.0,
 17534.0,
 17537.0,
 17538.0,
 17540.0,
 17545.0,
 17549.0,
 17552.0,
 17554.0,
 17555.0,
 17557.0,
 17560.0,
 17561.0,
 17562.0,
 17564.0,
 17566.0,
 17567.0,
 17571.0,
 17572.0,
 17573.0,
 17576.0,
 17579.0,
 17581.0,
 17584.0,
 17589.0,
 17590.0,
 17591.0,
 17593.0,
 17594.0,
 17595.0,
 17596.0,
 17600.0,
 17602.0,
 17603.0,
 17608.0,
 17609.0,
 17611.0,
 17612.0,
 17613.0,
 17614.0,
 17618.0,
 17620.0,
 17621.0,
 17623.0,
 17624.0,
 17625.0,
 17628.0,
 17629.0,
 17631.0,
 17633.0,
 17634.0,
 17636.0,
 17637.0,
 17640.0,
 17644.0,
 17647.0,
 17648.0,
 17650.0,
 17651.0,
 17652.0,
 17653.0,
 17655.0,
 17656.0,
 17658.0,
 17659.0,
 17663.0,
 17664.0,
 17666.0,
 17667.0,
 17668.0,
 17669.0,
 17671.0,
 17672.0,
 17673.0,
 17674.0,
 17675.0,
 17676.0,
 17677.0,
 17679.0,
 17680.0,
 17682.0,
 17684.0,
 17685.0,
 17686.0,
 17690.0,
 17696.0,
 17700.0,
 17702.0,
 17703.0,
 17705.0,
 17706.0,
 17711.0,
 17712.0,
 17716.0,
 17719.0,
 17720.0,
 17722.0,
 17724.0,
 17725.0,
 17727.0,
 17728.0,
 17730.0,
 17731.0,
 17733.0,
 17734.0,
 17735.0,
 17736.0,
 17737.0,
 17738.0,
 17739.0,
 17744.0,
 17750.0,
 17754.0,
 17757.0,
 17758.0,
 17759.0,
 17760.0,
 17761.0,
 17764.0,
 17767.0,
 17768.0,
 17769.0,
 17771.0,
 17772.0,
 17774.0,
 17777.0,
 17779.0,
 17783.0,
 17785.0,
 17786.0,
 17788.0,
 17790.0,
 17791.0,
 17793.0,
 17796.0,
 17797.0,
 17799.0,
 17800.0,
 17802.0,
 17805.0,
 17806.0,
 17809.0,
 17811.0,
 17812.0,
 17813.0,
 17816.0,
 17817.0,
 17819.0,
 17824.0,
 17827.0,
 17828.0,
 17830.0,
 17831.0,
 17832.0,
 17835.0,
 17836.0,
 17837.0,
 17838.0,
 17839.0,
 17841.0,
 17846.0,
 17848.0,
 17852.0,
 17856.0,
 17857.0,
 17858.0,
 17861.0,
 17863.0,
 17864.0,
 17865.0,
 17867.0,
 17870.0,
 17873.0,
 17878.0,
 17883.0,
 17884.0,
 17885.0,
 17886.0,
 17888.0,
 17892.0,
 17894.0,
 17895.0,
 17896.0,
 17898.0,
 17901.0,
 17904.0,
 17905.0,
 17911.0,
 17913.0,
 17914.0,
 17917.0,
 17919.0,
 17920.0,
 17921.0,
 17924.0,
 17928.0,
 17929.0,
 17930.0,
 17932.0,
 17934.0,
 17936.0,
 17937.0,
 17940.0,
 17942.0,
 17947.0,
 17949.0,
 17950.0,
 17951.0,
 17954.0,
 17957.0,
 17961.0,
 17964.0,
 17965.0,
 17966.0,
 17973.0,
 17974.0,
 17975.0,
 17977.0,
 17979.0,
 17985.0,
 17986.0,
 17988.0,
 17997.0,
 17999.0,
 18001.0,
 18005.0,
 18006.0,
 18008.0,
 18014.0,
 18015.0,
 18016.0,
 18017.0,
 18019.0,
 18022.0,
 18027.0,
 18030.0,
 18033.0,
 18034.0,
 18035.0,
 18036.0,
 18040.0,
 18041.0,
 18042.0,
 18043.0,
 18044.0,
 18045.0,
 18053.0,
 18055.0,
 18058.0,
 18059.0,
 18061.0,
 18065.0,
 18066.0,
 18067.0,
 18069.0,
 18075.0,
 18077.0,
 18079.0,
 18080.0,
 18081.0,
 18082.0,
 18084.0,
 18087.0,
 18088.0,
 18092.0,
 18093.0,
 18094.0,
 18096.0,
 18097.0,
 18101.0,
 18102.0,
 18104.0,
 18105.0,
 18109.0,
 18110.0,
 18112.0,
 18116.0,
 18117.0,
 18118.0,
 18122.0,
 18123.0,
 18125.0,
 18126.0,
 18127.0,
 18130.0,
 18135.0,
 18136.0,
 18139.0,
 18144.0,
 18145.0,
 18147.0,
 18149.0,
 18150.0,
 18154.0,
 18155.0,
 18156.0,
 18158.0,
 18160.0,
 18161.0,
 18164.0,
 18167.0,
 18169.0,
 18170.0,
 18171.0,
 18172.0,
 18173.0,
 18174.0,
 18177.0,
 18179.0,
 18180.0,
 18181.0,
 18184.0,
 18188.0,
 18189.0,
 18192.0,
 18194.0,
 18196.0,
 18198.0,
 18204.0,
 18205.0,
 18209.0,
 18210.0,
 18211.0,
 18215.0,
 18216.0,
 18217.0,
 18219.0,
 18221.0,
 18222.0,
 18223.0,
 18225.0,
 18226.0,
 18228.0,
 18229.0,
 18230.0,
 18232.0,
 18235.0,
 18236.0,
 18237.0,
 18240.0,
 18241.0,
 18242.0,
 18245.0,
 18246.0,
 18249.0,
 18251.0,
 18252.0,
 18255.0,
 18257.0,
 18259.0,
 18261.0,
 18263.0,
 18265.0,
 18270.0,
 18272.0,
 18273.0,
 18274.0,
 18276.0,
 18277.0,
 18278.0,
 18282.0,
 18283.0,
 18287.0,
 12347.0,
 12348.0,
 12349.0,
 12352.0,
 12356.0,
 12357.0,
 12358.0,
 12359.0,
 12360.0,
 12362.0,
 12364.0,
 12367.0,
 12370.0,
 12371.0,
 12372.0,
 12374.0,
 12375.0,
 12379.0,
 12380.0,
 12381.0,
 12384.0,
 12388.0,
 12390.0,
 12391.0,
 12393.0,
 12394.0,
 12395.0,
 12397.0,
 12398.0,
 12403.0,
 12406.0,
 12407.0,
 12408.0,
 12409.0,
 12412.0,
 12413.0,
 12415.0,
 12417.0,
 12420.0,
 12421.0,
 12422.0,
 12423.0,
 12425.0,
 12427.0,
 12428.0,
 12429.0,
 12430.0,
 12431.0,
 12432.0,
 12433.0,
 12434.0,
 12435.0,
 12436.0,
 12437.0,
 12438.0,
 12442.0,
 12444.0,
 12445.0,
 12446.0,
 ...]

Create the labels for the customers from training_data

In [6]:
target_values = []
for customer_id in training_data['CustomerID']:
    if customer_id not in temp0_customer_ids:
        target_values.append('Churn')
    else:
        target_values.append('Not Churn')
training_data['Target'] = target_values
training_data

/var/folders/hz/r3x824916lx2gwqnf6vhdcc00000gp/T/ipykernel_57806/1019097770.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_data['Target'] = target_values

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Target
0,536365.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,Churn
1,536365.0,71053.0,WHITE METAL LANTERN,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,Churn
2,536365.0,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,Churn
3,536365.0,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,Churn
4,536365.0,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,Churn
...,...,...,...,...,...,...,...,...,...
319395,564852.0,82552.0,WASHROOM METAL SIGN,10.0,2011-08-30 17:23:00,1.45,14976.0,United Kingdom,Not Churn
319396,564852.0,21756.0,BATH BUILDING BLOCK WORD,3.0,2011-08-30 17:23:00,5.95,14976.0,United Kingdom,Not Churn
319397,564852.0,21908.0,CHOCOLATE THIS WAY METAL SIGN,7.0,2011-08-30 17:23:00,2.10,14976.0,United Kingdom,Not Churn
319398,564852.0,22116.0,METAL SIGN HIS DINNER IS SERVED,10.0,2011-08-30 17:23:00,0.79,14976.0,United Kingdom,Not Churn
319399,564852.0,23091.0,ZINC HERB GARDEN CONTAINER,2.0,2011-08-30 17:23:00,6.25,14976.0,United Kingdom,Not Churn

Filter the attributes required for training the models

In [7]:
training_features = training_data[['Quantity', 'UnitPrice', 'Country', 'Target']]
training_features

        Quantity  UnitPrice         Country     Target
0            6.0       2.55  United Kingdom      Churn
1            6.0       3.39  United Kingdom      Churn
2            8.0       2.75  United Kingdom      Churn
3            6.0       3.39  United Kingdom      Churn
4            6.0       3.39  United Kingdom      Churn
...          ...        ...             ...        ...
319395      10.0       1.45  United Kingdom  Not Churn
319396       3.0       5.95  United Kingdom  Not Churn
319397       7.0       2.10  United Kingdom  Not Churn
319398      10.0       0.79  United Kingdom  Not Churn
319399       2.0       6.25  United Kingdom  Not Churn

[231183 rows x 4 columns]

Assign labels to values from attributes 'Quantity' and 'UnitPrice'

In [8]:
temp0 = list(training_features['UnitPrice'].values)
mid0 = sum(temp0) / len(temp0)

temp1 = [i for i in temp0 if i < mid0]
temp2 = [i for i in temp0 if i >= mid0]
mid1 = sum(temp1) / len(temp1)
mid2 = sum(temp2) / len(temp2)

new_unitPrice = []
for unitPrice in temp0:
    if unitPrice < mid1:
        new_unitPrice.append('low')
    elif unitPrice > mid1 and unitPrice < mid2:
        new_unitPrice.append('medium')
    else:
        new_unitPrice.append('high')

In [9]:
temp0 = list(training_features['Quantity'].values)
mid0 = sum(temp0) / len(temp0)

temp1 = [i for i in temp0 if i < mid0]
temp2 = [i for i in temp0 if i >= mid0]
mid1 = sum(temp1) / len(temp1)
mid2 = sum(temp2) / len(temp2)

new_quantity = []
for quantity in temp0:
    if quantity < mid1:
        new_quantity.append('low')
    elif quantity > mid1 and unitPrice < mid2:
        new_quantity.append('medium')
    else:
        new_quantity.append('high')

In [10]:
training_features['UnitPrice'] = new_unitPrice
training_features['Quantity'] = new_quantity

/var/folders/hz/r3x824916lx2gwqnf6vhdcc00000gp/T/ipykernel_57806/3200418754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features['UnitPrice'] = new_unitPrice
/var/folders/hz/r3x824916lx2gwqnf6vhdcc00000gp/T/ipykernel_57806/3200418754.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features['Quantity'] = new_quantity

Save the dataframe 'training_features' as csv file

In [11]:
training_features.to_csv('data.csv')

In [12]:
df = pd.read_csv('data.csv')
df = df.drop(['Unnamed: 0'], axis=1)
df.head()

  Quantity UnitPrice         Country Target
0   medium    medium  United Kingdom  Churn
1   medium    medium  United Kingdom  Churn
2   medium    medium  United Kingdom  Churn
3   medium    medium  United Kingdom  Churn
4   medium    medium  United Kingdom  Churn

Split the dataframe into training and testing set

In [13]:
train_size = int(len(df) * 0.80)
train_size

184946

In [14]:
train = df[:train_size]
test = df[train_size:]

Function for calculating the entropy of the entire or subset of the dataframe

In [15]:
def get_entropy_of_dataset(df):
    labels = df.iloc[:,-1].values
    distinct_labels = {}

    for label in labels:
        if label not in distinct_labels:
            distinct_labels[label] = 1
        else:
            distinct_labels[label] += 1

    entropy = 0
    length = len(labels)
    for distinct_label in distinct_labels:
        pi = distinct_labels[distinct_label] / length
        entropy += (-pi) * np.log2(pi)

    return entropy

Function for calculating the average information of a specific attribute

In [16]:
def get_avg_info_of_attribute(df, attribute):
    attribute_values = list(set(df[attribute].values))
    total_length = len(df)
    average_info = 0

    for attribute_value in attribute_values:
        temp_df = df[df[attribute] == attribute_value]
        entropy = get_entropy_of_dataset(temp_df)
        average_info += ((len(temp_df) / total_length) * entropy)

    return average_info

Function for calculating the Information gain of a specific attribute

In [17]:
def get_information_gain(df, attribute):
    return get_entropy_of_dataset(df) - get_avg_info_of_attribute(df, attribute)

Function for selecting an attribute with highest information gain

In [18]:
def get_selected_attribute(df):
    attributes = list(df.columns[:-1].values)
    igs = []
    
    for attribute in attributes:
        igs.append(get_information_gain(df, attribute))

    max_index = igs.index(max(igs))
    return attributes[max_index]

Function for creating the tree (Tree is created using the datatype 'dict')

In [19]:
def make_tree(df):
    if get_entropy_of_dataset(df) == 0:
        return ''.join(list(set(df.iloc[:,-1].values)))
    if len(df.columns.values) == 1:
        values = list(df.iloc[:,-1].values)
        return ''.join(list(max(values, key= lambda x : values.count(x))))
    if df.empty:
        return []
    tree = {}
    attribute = get_selected_attribute(df)
    attribute_values = list(set(df[attribute].values))
    
    tree[attribute] = {}
    for attribute_value in attribute_values:
        temp_df = df[df[attribute] == attribute_value]
        temp_df = temp_df.drop([attribute], axis = 1)
        tree[attribute][attribute_value] = make_tree(temp_df)

    return tree

Function for predicting the label of a given instance using the tree created.

In [20]:
def pred(tree, instance):
    sub_tree = tree
    while type(sub_tree) != str:
        attribute = list(sub_tree.keys())[0]
        attribute_value = instance[attribute]
        sub_tree = sub_tree[attribute][attribute_value]

    return sub_tree

Function for evaluating the accuracy of the decision tree.

In [21]:
def evaluate(tree, test):
    length = len(test)
    correct = 0

    for i in range(length):
        prediction = pred(tree, test.iloc[i])
        if prediction == test.iloc[i, -1]:
            correct += 1

    return (correct / length) * 100

Create the tree

In [22]:
tree = make_tree(train)
tree

{'Country': {'Norway': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'Channel Islands': {'UnitPrice': {'medium': {'Quantity': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'high': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}},
    'low': {'Quantity': {'medium': 'Not Churn'}}}},
  'Lebanon': 'Churn',
  'Belgium': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'Cyprus': {'UnitPrice': {'medium': {'Quantity': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'high': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}},
    'low': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}}}},
  'Israel': 'Churn',
  'European Community': 'Churn',
  'Czech Republic': 'Not Churn',
  'Japan': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Churn',
      'high': 'Churn',
      'low': 'Churn'}}}},
  'Malta': 'Not Churn',
  'Finland': {'UnitPrice': {'medium': {'Quantity': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'high': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}},
    'low': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}}}},
  'Brazil': 'Churn',
  'Austria': {'UnitPrice': {'medium': {'Quantity': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'high': {'Quantity': {'medium': 'Not Churn', 'low': 'Churn'}},
    'low': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}}}},
  'Greece': 'Churn',
  'Canada': 'Churn',
  'Saudi Arabia': 'Churn',
  'Portugal': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'Unspecified': 'Churn',
  'France': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'Denmark': 'Not Churn',
  'Germany': {'UnitPrice': {'medium': {'Quantity': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'high': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}},
    'low': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}}}},
  'EIRE': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'Australia': {'UnitPrice': {'medium': {'Quantity': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'high': 'Not Churn',
    'low': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}}}},
  'Italy': {'UnitPrice': {'medium': {'Quantity': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'high': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}},
    'low': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}}}},
  'Iceland': 'Not Churn',
  'Netherlands': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'United Arab Emirates': 'Churn',
  'Bahrain': 'Churn',
  'Sweden': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'Switzerland': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'Singapore': 'Not Churn',
  'USA': 'Churn',
  'Poland': {'UnitPrice': {'medium': {'Quantity': {'medium': 'Not Churn',
      'low': 'Not Churn'}},
    'high': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}},
    'low': {'Quantity': {'medium': 'Not Churn', 'low': 'Not Churn'}}}},
  'United Kingdom': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}},
  'Lithuania': 'Churn',
  'Spain': {'Quantity': {'medium': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}},
    'low': {'UnitPrice': {'medium': 'Not Churn',
      'high': 'Not Churn',
      'low': 'Not Churn'}}}}}}

Evaluate the tree

In [23]:
tree_accuracy = evaluate(tree, test)
tree_accuracy

85.19583883037394

Decision Tree(ID3) Accuracy = 85.19

Training the ANN model

In [24]:
training_features = training_data[['Quantity', 'UnitPrice', 'Country', 'Target']]

In [25]:
le0 = LabelEncoder()
training_features['Country'] = le0.fit_transform(training_features['Country'])
le1 = LabelEncoder()
training_features['Target'] = le1.fit_transform(training_features['Target'])

/var/folders/hz/r3x824916lx2gwqnf6vhdcc00000gp/T/ipykernel_57806/1639887391.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features['Country'] = le0.fit_transform(training_features['Country'])
/var/folders/hz/r3x824916lx2gwqnf6vhdcc00000gp/T/ipykernel_57806/1639887391.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_features['Target'] = le1.fit_transform(training_features['Target'])

In [26]:
x = training_features.iloc[:,:-1].values
y = training_features.iloc[:,-1].values
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=0)

In [27]:
ann_model = Sequential()
ann_model.add(Dense(4, activation='relu'))
ann_model.add(Dense(10, activation='relu'))
ann_model.add(Dense(1, activation='sigmoid'))

2022-11-09 09:02:23.652908: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [28]:
ann_model.compile(loss = 'mse', optimizer = 'adam', metrics=['accuracy'])
ann_model.fit(xtrain, ytrain, epochs = 1, batch_size = 1, verbose = 1)

184946/184946 [==============================] - 123s 663us/step - loss: 0.1560 - accuracy: 0.8077

In [29]:
y_pred = ann_model.predict(xtest)
correct = 0
for i in range(len(y_pred)):
    if y_pred[i] > 0.50:
        y_pred[i] = 1
    else:
        y_pred[i] = 0
for i in range(len(y_pred)):
    if y_pred[i] == ytest[i]:
        correct += 1

ann_accuracy = (correct / len(y_pred)) * 100
ann_accuracy

1445/1445 [==============================] - 1s 572us/step

80.70592815277809

ANN Model Accuracy = 80.7

Train the SVM model

In [30]:
svm_model = SVC(kernel='rbf')
svm_model.fit(xtrain, ytrain)

SVC()

In [31]:
print(accuracy_score(ytest, svm_model.predict(xtest)))

0.8070376538270216

SVM Model Accuracy = 80.70

Model Comparison (Accuracy)
- Decision Tree = 85.19
- ANN Model = 80.70
- SVM Model = 80.70